version: 2.1
orbs:
  docker: circleci/docker@1.7.0
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
jobs:
  my-job-name:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          pwd
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          image: akshay         
workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
      - example-job

